name: Customer Support API ETL

on:
  workflow_dispatch:   # Allow manual trigger
  schedule:
    - cron: '0 * * * *' # (optional) Every hour

jobs:
  etl_api:
    runs-on: ubuntu-latest
    env:
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_DB: ${{ secrets.MYSQL_DB }}
      PG_USER: ${{ secrets.PG_USER }}
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      PG_HOST: ${{ secrets.PG_HOST }}
      PG_DB: ${{ secrets.PG_DB }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install nbconvert

      - name: Run API ETL Jupyter Notebook
        run: |
          jupyter nbconvert --to script notebooks/customer_support_API_Extract_Load_Raw.ipynb
          python notebooks/customer_support_API_Extract_Load_Raw.py
